export const COUNTRIES = [
  { name: "Afghanistan", cca2: "AF", callingCode: ["93"], flag: "🇦🇫" },
  { name: "Åland Islands", cca2: "AX", callingCode: ["358"], flag: "🇦🇽" },
  { name: "Albania", cca2: "AL", callingCode: ["355"], flag: "🇦🇱" },
  { name: "Algeria", cca2: "DZ", callingCode: ["213"], flag: "🇩🇿" },
  { name: "American Samoa", cca2: "AS", callingCode: ["1684"], flag: "🇦🇸" },
  { name: "Andorra", cca2: "AD", callingCode: ["376"], flag: "🇦🇩" },
  { name: "Angola", cca2: "AO", callingCode: ["244"], flag: "🇦🇴" },
  { name: "Anguilla", cca2: "AI", callingCode: ["1264"], flag: "🇦🇮" },
  { name: "Antarctica", cca2: "AQ", callingCode: ["672"], flag: "🇦🇶" },
  { name: "Antigua and Barbuda", cca2: "AG", callingCode: ["1268"], flag: "🇦🇬" },
  { name: "Argentina", cca2: "AR", callingCode: ["54"], flag: "🇦🇷" },
  { name: "Armenia", cca2: "AM", callingCode: ["374"], flag: "🇦🇲" },
  { name: "Aruba", cca2: "AW", callingCode: ["297"], flag: "🇦🇼" },
  { name: "Australia", cca2: "AU", callingCode: ["61"], flag: "🇦🇺" },
  { name: "Austria", cca2: "AT", callingCode: ["43"], flag: "🇦🇹" },
  { name: "Azerbaijan", cca2: "AZ", callingCode: ["994"], flag: "🇦🇿" },
  { name: "Bahamas", cca2: "BS", callingCode: ["1242"], flag: "🇧🇸" },
  { name: "Bahrain", cca2: "BH", callingCode: ["973"], flag: "🇧🇭" },
  { name: "Bangladesh", cca2: "BD", callingCode: ["880"], flag: "🇧🇩" },
  { name: "Barbados", cca2: "BB", callingCode: ["1246"], flag: "🇧🇧" },
  { name: "Belarus", cca2: "BY", callingCode: ["375"], flag: "🇧🇾" },
  { name: "Belgium", cca2: "BE", callingCode: ["32"], flag: "🇧🇪" },
  { name: "Belize", cca2: "BZ", callingCode: ["501"], flag: "🇧🇿" },
  { name: "Benin", cca2: "BJ", callingCode: ["229"], flag: "🇧🇯" },
  { name: "Bermuda", cca2: "BM", callingCode: ["1441"], flag: "🇧🇲" },
  { name: "Bhutan", cca2: "BT", callingCode: ["975"], flag: "🇧🇹" },
  { name: "Bolivia", cca2: "BO", callingCode: ["591"], flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", cca2: "BA", callingCode: ["387"], flag: "🇧🇦" },
  { name: "Botswana", cca2: "BW", callingCode: ["267"], flag: "🇧🇼" },
  { name: "Bouvet Island", cca2: "BV", callingCode: ["47"], flag: "🇧🇻" },
  { name: "Brazil", cca2: "BR", callingCode: ["55"], flag: "🇧🇷" },
  { name: "British Indian Ocean Territory", cca2: "IO", callingCode: ["246"], flag: "🇮🇴" },
  { name: "Brunei Darussalam", cca2: "BN", callingCode: ["673"], flag: "🇧🇳" },
  { name: "Bulgaria", cca2: "BG", callingCode: ["359"], flag: "🇧🇬" },
  { name: "Burkina Faso", cca2: "BF", callingCode: ["226"], flag: "🇧🇫" },
  { name: "Burundi", cca2: "BI", callingCode: ["257"], flag: "🇧🇮" },
  { name: "Cambodia", cca2: "KH", callingCode: ["855"], flag: "🇰🇭" },
  { name: "Cameroon", cca2: "CM", callingCode: ["237"], flag: "🇨🇲" },
  { name: "Canada", cca2: "CA", callingCode: ["1"], flag: "🇨🇦" },
  { name: "Cape Verde", cca2: "CV", callingCode: ["238"], flag: "🇨🇻" },
  { name: "Cayman Islands", cca2: "KY", callingCode: ["1345"], flag: "🇰🇾" },
  { name: "Central African Republic", cca2: "CF", callingCode: ["236"], flag: "🇨🇫" },
  { name: "Chad", cca2: "TD", callingCode: ["235"], flag: "🇹🇩" },
  { name: "Chile", cca2: "CL", callingCode: ["56"], flag: "🇨🇱" },
  { name: "China", cca2: "CN", callingCode: ["86"], flag: "🇨🇳" },
  { name: "Christmas Island", cca2: "CX", callingCode: ["61"], flag: "🇨🇽" },
  { name: "Cocos (Keeling) Islands", cca2: "CC", callingCode: ["61"], flag: "🇨🇨" },
  { name: "Colombia", cca2: "CO", callingCode: ["57"], flag: "🇨🇴" },
  { name: "Comoros", cca2: "KM", callingCode: ["269"], flag: "🇰🇲" },
  { name: "Congo", cca2: "CG", callingCode: ["242"], flag: "🇨🇬" },
  { name: "Congo, The Democratic Republic of the", cca2: "CD", callingCode: ["243"], flag: "🇨🇩" },
  { name: "Cook Islands", cca2: "CK", callingCode: ["682"], flag: "🇨🇰" },
  { name: "Costa Rica", cca2: "CR", callingCode: ["506"], flag: "🇨🇷" },
  { name: "Côte d'Ivoire", cca2: "CI", callingCode: ["225"], flag: "🇨🇮" },
  { name: "Croatia", cca2: "HR", callingCode: ["385"], flag: "🇭🇷" },
  { name: "Cuba", cca2: "CU", callingCode: ["53"], flag: "🇨🇺" },
  { name: "Curaçao", cca2: "CW", callingCode: ["599"], flag: "🇨🇼" },
  { name: "Cyprus", cca2: "CY", callingCode: ["357"], flag: "🇨🇾" },
  { name: "Czech Republic", cca2: "CZ", callingCode: ["420"], flag: "🇨🇿" },
  { name: "Denmark", cca2: "DK", callingCode: ["45"], flag: "🇩🇰" },
  { name: "Djibouti", cca2: "DJ", callingCode: ["253"], flag: "🇩🇯" },
  { name: "Dominica", cca2: "DM", callingCode: ["1767"], flag: "🇩🇲" },
  { name: "Dominican Republic", cca2: "DO", callingCode: ["1809"], flag: "🇩🇴" },
  { name: "Ecuador", cca2: "EC", callingCode: ["593"], flag: "🇪🇨" },
  { name: "Egypt", cca2: "EG", callingCode: ["20"], flag: "🇪🇬" },
  { name: "El Salvador", cca2: "SV", callingCode: ["503"], flag: "🇸🇻" },
  { name: "Equatorial Guinea", cca2: "GQ", callingCode: ["240"], flag: "🇬🇶" },
  { name: "Eritrea", cca2: "ER", callingCode: ["291"], flag: "🇪🇷" },
  { name: "Estonia", cca2: "EE", callingCode: ["372"], flag: "🇪🇪" },
  { name: "Ethiopia", cca2: "ET", callingCode: ["251"], flag: "🇪🇹" },
  { name: "Falkland Islands (Malvinas)", cca2: "FK", callingCode: ["500"], flag: "🇫🇰" },
  { name: "Faroe Islands", cca2: "FO", callingCode: ["298"], flag: "🇫🇴" },
  { name: "Fiji", cca2: "FJ", callingCode: ["679"], flag: "🇫🇯" },
  { name: "Finland", cca2: "FI", callingCode: ["358"], flag: "🇫🇮" },
  { name: "France", cca2: "FR", callingCode: ["33"], flag: "🇫🇷" },
  { name: "French Guiana", cca2: "GF", callingCode: ["594"], flag: "🇬🇫" },
  { name: "French Polynesia", cca2: "PF", callingCode: ["689"], flag: "🇵🇫" },
  { name: "French Southern Territories", cca2: "TF", callingCode: ["262"], flag: "🇹🇫" },
  { name: "Gabon", cca2: "GA", callingCode: ["241"], flag: "🇬🇦" },
  { name: "Gambia", cca2: "GM", callingCode: ["220"], flag: "🇬🇲" },
  { name: "Georgia", cca2: "GE", callingCode: ["995"], flag: "🇬🇪" },
  { name: "Ghana", cca2: "GH", callingCode: ["233"], flag: "🇬🇭" },
  { name: "Gibraltar", cca2: "GI", callingCode: ["350"], flag: "🇬🇮" },
  { name: "Greece", cca2: "GR", callingCode: ["30"], flag: "🇬🇷" },
  { name: "Greenland", cca2: "GL", callingCode: ["299"], flag: "🇬🇱" },
  { name: "Grenada", cca2: "GD", callingCode: ["1473"], flag: "🇬🇩" },
  { name: "Guadeloupe", cca2: "GP", callingCode: ["590"], flag: "🇬🇵" },
  { name: "Guam", cca2: "GU", callingCode: ["1671"], flag: "🇬🇺" },
  { name: "Guatemala", cca2: "GT", callingCode: ["502"], flag: "🇬🇹" },
  { name: "Guernsey", cca2: "GG", callingCode: ["44"], flag: "🇬🇬" },
  { name: "Guinea", cca2: "GN", callingCode: ["224"], flag: "🇬🇳" },
  { name: "Guinea-Bissau", cca2: "GW", callingCode: ["245"], flag: "🇬🇼" },
  { name: "Guyana", cca2: "GY", callingCode: ["592"], flag: "🇬🇾" },
  { name: "Haiti", cca2: "HT", callingCode: ["509"], flag: "🇭🇹" },
  { name: "Heard Island and McDonald Islands", cca2: "HM", callingCode: ["672"], flag: "🇭🇲" },
  { name: "Holy See (Vatican City State)", cca2: "VA", callingCode: ["39"], flag: "🇻🇦" },
  { name: "Honduras", cca2: "HN", callingCode: ["504"], flag: "🇭🇳" },
  { name: "Hong Kong", cca2: "HK", callingCode: ["852"], flag: "🇭🇰" },
  { name: "Hungary", cca2: "HU", callingCode: ["36"], flag: "🇭🇺" },
  { name: "Iceland", cca2: "IS", callingCode: ["354"], flag: "🇮🇸" },
  { name: "India", cca2: "IN", callingCode: ["91"], flag: "🇮🇳" },
  { name: "Indonesia", cca2: "ID", callingCode: ["62"], flag: "🇮🇩" },
  { name: "Iran, Islamic Republic of", cca2: "IR", callingCode: ["98"], flag: "🇮🇷" },
  { name: "Iraq", cca2: "IQ", callingCode: ["964"], flag: "🇮🇶" },
  { name: "Ireland", cca2: "IE", callingCode: ["353"], flag: "🇮🇪" },
  { name: "Isle of Man", cca2: "IM", callingCode: ["44"], flag: "🇮🇲" },
  { name: "Israel", cca2: "IL", callingCode: ["972"], flag: "🇮🇱" },
  { name: "Italy", cca2: "IT", callingCode: ["39"], flag: "🇮🇹" },
  { name: "Jamaica", cca2: "JM", callingCode: ["1876"], flag: "🇯🇲" },
  { name: "Japan", cca2: "JP", callingCode: ["81"], flag: "🇯🇵" },
  { name: "Jersey", cca2: "JE", callingCode: ["44"], flag: "🇯🇪" },
  { name: "Jordan", cca2: "JO", callingCode: ["962"], flag: "🇯🇴" },
  { name: "Kazakhstan", cca2: "KZ", callingCode: ["7"], flag: "🇰🇿" },
  { name: "Kenya", cca2: "KE", callingCode: ["254"], flag: "🇰🇪" },
  { name: "Kiribati", cca2: "KI", callingCode: ["686"], flag: "🇰🇮" },
  { name: "Korea, Democratic People's Republic of", cca2: "KP", callingCode: ["850"], flag: "🇰🇵" },
  { name: "Korea, Republic of", cca2: "KR", callingCode: ["82"], flag: "🇰🇷" },
  { name: "Kuwait", cca2: "KW", callingCode: ["965"], flag: "🇰🇼" },
  { name: "Kyrgyzstan", cca2: "KG", callingCode: ["996"], flag: "🇰🇬" },
  { name: "Lao People's Democratic Republic", cca2: "LA", callingCode: ["856"], flag: "🇱🇦" },
  { name: "Latvia", cca2: "LV", callingCode: ["371"], flag: "🇱🇻" },
  { name: "Lebanon", cca2: "LB", callingCode: ["961"], flag: "🇱🇧" },
  { name: "Lesotho", cca2: "LS", callingCode: ["266"], flag: "🇱🇸" },
  { name: "Liberia", cca2: "LR", callingCode: ["231"], flag: "🇱🇷" },
  { name: "Libya", cca2: "LY", callingCode: ["218"], flag: "🇱🇾" },
  { name: "Liechtenstein", cca2: "LI", callingCode: ["423"], flag: "🇱🇮" },
  { name: "Lithuania", cca2: "LT", callingCode: ["370"], flag: "🇱🇹" },
  { name: "Luxembourg", cca2: "LU", callingCode: ["352"], flag: "🇱🇺" },
  { name: "Macao", cca2: "MO", callingCode: ["853"], flag: "🇲🇴" },
  { name: "Macedonia, The Former Yugoslav Republic of", cca2: "MK", callingCode: ["389"], flag: "🇲🇰" },
  { name: "Madagascar", cca2: "MG", callingCode: ["261"], flag: "🇲🇬" },
  { name: "Malawi", cca2: "MW", callingCode: ["265"], flag: "🇲🇼" },
  { name: "Malaysia", cca2: "MY", callingCode: ["60"], flag: "🇲🇾" },
  { name: "Maldives", cca2: "MV", callingCode: ["960"], flag: "🇲🇻" },
  { name: "Mali", cca2: "ML", callingCode: ["223"], flag: "🇲🇱" },
  { name: "Malta", cca2: "MT", callingCode: ["356"], flag: "🇲🇹" },
  { name: "Marshall Islands", cca2: "MH", callingCode: ["692"], flag: "🇲🇭" },
  { name: "Martinique", cca2: "MQ", callingCode: ["596"], flag: "🇲🇶" },
  { name: "Mauritania", cca2: "MR", callingCode: ["222"], flag: "🇲🇷" },
  { name: "Mauritius", cca2: "MU", callingCode: ["230"], flag: "🇲🇺" },
  { name: "Mayotte", cca2: "YT", callingCode: ["262"], flag: "🇾🇹" },
  { name: "Mexico", cca2: "MX", callingCode: ["52"], flag: "🇲🇽" },
  { name: "Micronesia, Federated States of", cca2: "FM", callingCode: ["691"], flag: "🇫🇲" },
  { name: "Moldova, Republic of", cca2: "MD", callingCode: ["373"], flag: "🇲🇩" },
  { name: "Monaco", cca2: "MC", callingCode: ["377"], flag: "🇲🇨" },
  { name: "Mongolia", cca2: "MN", callingCode: ["976"], flag: "🇲🇳" },
  { name: "Montenegro", cca2: "ME", callingCode: ["382"], flag: "🇲🇪" },
  { name: "Montserrat", cca2: "MS", callingCode: ["1664"], flag: "🇲🇸" },
  { name: "Morocco", cca2: "MA", callingCode: ["212"], flag: "🇲🇦" },
  { name: "Mozambique", cca2: "MZ", callingCode: ["258"], flag: "🇲🇿" },
  { name: "Myanmar", cca2: "MM", callingCode: ["95"], flag: "🇲🇲" },
  { name: "Namibia", cca2: "NA", callingCode: ["264"], flag: "🇳🇦" },
  { name: "Nauru", cca2: "NR", callingCode: ["674"], flag: "🇳🇷" },
  { name: "Nepal", cca2: "NP", callingCode: ["977"], flag: "🇳🇵" },
  { name: "Netherlands", cca2: "NL", callingCode: ["31"], flag: "🇳🇱" },
  { name: "New Caledonia", cca2: "NC", callingCode: ["687"], flag: "🇳🇨" },
  { name: "New Zealand", cca2: "NZ", callingCode: ["64"], flag: "🇳🇿" },
  { name: "Nicaragua", cca2: "NI", callingCode: ["505"], flag: "🇳🇮" },
  { name: "Niger", cca2: "NE", callingCode: ["227"], flag: "🇳🇪" },
  { name: "Nigeria", cca2: "NG", callingCode: ["234"], flag: "🇳🇬" },
  { name: "Niue", cca2: "NU", callingCode: ["683"], flag: "🇳🇺" },
  { name: "Norfolk Island", cca2: "NF", callingCode: ["672"], flag: "🇳🇫" },
  { name: "Northern Mariana Islands", cca2: "MP", callingCode: ["1670"], flag: "🇲🇵" },
  { name: "Norway", cca2: "NO", callingCode: ["47"], flag: "🇳🇴" },
  { name: "Oman", cca2: "OM", callingCode: ["968"], flag: "🇴🇲" },
  { name: "Pakistan", cca2: "PK", callingCode: ["92"], flag: "🇵🇰" },
  { name: "Palau", cca2: "PW", callingCode: ["680"], flag: "🇵🇼" },
  { name: "Palestine, State of", cca2: "PS", callingCode: ["970"], flag: "🇵🇸" },
  { name: "Panama", cca2: "PA", callingCode: ["507"], flag: "🇵🇦" },
  { name: "Papua New Guinea", cca2: "PG", callingCode: ["675"], flag: "🇵🇬" },
  { name: "Paraguay", cca2: "PY", callingCode: ["595"], flag: "🇵🇾" },
  { name: "Peru", cca2: "PE", callingCode: ["51"], flag: "🇵🇪" },
  { name: "Philippines", cca2: "PH", callingCode: ["63"], flag: "🇵🇭" },
  { name: "Pitcairn", cca2: "PN", callingCode: ["64"], flag: "🇵🇳" },
  { name: "Poland", cca2: "PL", callingCode: ["48"], flag: "🇵🇱" },
  { name: "Portugal", cca2: "PT", callingCode: ["351"], flag: "🇵🇹" },
  { name: "Puerto Rico", cca2: "PR", callingCode: ["1"], flag: "🇵🇷" },
  { name: "Qatar", cca2: "QA", callingCode: ["974"], flag: "🇶🇦" },
  { name: "Réunion", cca2: "RE", callingCode: ["262"], flag: "🇷🇪" },
  { name: "Romania", cca2: "RO", callingCode: ["40"], flag: "🇷🇴" },
  { name: "Russian Federation", cca2: "RU", callingCode: ["7"], flag: "🇷🇺" },
  { name: "Rwanda", cca2: "RW", callingCode: ["250"], flag: "🇷🇼" },
  { name: "Saint Barthélemy", cca2: "BL", callingCode: ["590"], flag: "🇧🇱" },
  { name: "Saint Helena, Ascension and Tristan da Cunha", cca2: "SH", callingCode: ["290"], flag: "🇸🇭" },
  { name: "Saint Kitts and Nevis", cca2: "KN", callingCode: ["1869"], flag: "🇰🇳" },
  { name: "Saint Lucia", cca2: "LC", callingCode: ["1758"], flag: "🇱🇨" },
  { name: "Saint Martin (French part)", cca2: "MF", callingCode: ["590"], flag: "🇲🇫" },
  { name: "Saint Pierre and Miquelon", cca2: "PM", callingCode: ["508"], flag: "🇵🇲" },
  { name: "Saint Vincent and the Grenadines", cca2: "VC", callingCode: ["1784"], flag: "🇻🇨" },
  { name: "Samoa", cca2: "WS", callingCode: ["685"], flag: "🇼🇸" },
  { name: "San Marino", cca2: "SM", callingCode: ["378"], flag: "🇸🇲" },
  { name: "Sao Tome and Principe", cca2: "ST", callingCode: ["239"], flag: "🇸🇹" },
  { name: "Saudi Arabia", cca2: "SA", callingCode: ["966"], flag: "🇸🇦" },
  { name: "Senegal", cca2: "SN", callingCode: ["221"], flag: "🇸🇳" },
  { name: "Serbia", cca2: "RS", callingCode: ["381"], flag: "🇷🇸" },
  { name: "Seychelles", cca2: "SC", callingCode: ["248"], flag: "🇸🇨" },
  { name: "Sierra Leone", cca2: "SL", callingCode: ["232"], flag: "🇸🇱" },
  { name: "Singapore", cca2: "SG", callingCode: ["65"], flag: "🇸🇬" },
  { name: "Sint Maarten (Dutch part)", cca2: "SX", callingCode: ["1721"], flag: "🇸🇽" },
  { name: "Slovakia", cca2: "SK", callingCode: ["421"], flag: "🇸🇰" },
  { name: "Slovenia", cca2: "SI", callingCode: ["386"], flag: "🇸🇮" },
  { name: "Solomon Islands", cca2: "SB", callingCode: ["677"], flag: "🇸🇧" },
  { name: "Somalia", cca2: "SO", callingCode: ["252"], flag: "🇸🇴" },
  { name: "South Africa", cca2: "ZA", callingCode: ["27"], flag: "🇿🇦" },
  { name: "South Georgia and the South Sandwich Islands", cca2: "GS", callingCode: ["500"], flag: "🇬🇸" },
  { name: "South Sudan", cca2: "SS", callingCode: ["211"], flag: "🇸🇸" },
  { name: "Spain", cca2: "ES", callingCode: ["34"], flag: "🇪🇸" },
  { name: "Sri Lanka", cca2: "LK", callingCode: ["94"], flag: "🇱🇰" },
  { name: "Sudan", cca2: "SD", callingCode: ["249"], flag: "🇸🇩" },
  { name: "Suriname", cca2: "SR", callingCode: ["597"], flag: "🇸🇷" },
  { name: "Svalbard and Jan Mayen", cca2: "SJ", callingCode: ["47"], flag: "🇸🇯" },
  { name: "Swaziland", cca2: "SZ", callingCode: ["268"], flag: "🇸🇿" },
  { name: "Sweden", cca2: "SE", callingCode: ["46"], flag: "🇸🇪" },
  { name: "Switzerland", cca2: "CH", callingCode: ["41"], flag: "🇨🇭" },
  { name: "Syrian Arab Republic", cca2: "SY", callingCode: ["963"], flag: "🇸🇾" },
  { name: "Taiwan, Province of China", cca2: "TW", callingCode: ["886"], flag: "🇹🇼" },
  { name: "Tajikistan", cca2: "TJ", callingCode: ["992"], flag: "🇹🇯" },
  { name: "Tanzania, United Republic of", cca2: "TZ", callingCode: ["255"], flag: "🇹🇿" },
  { name: "Thailand", cca2: "TH", callingCode: ["66"], flag: "🇹🇭" },
  { name: "Timor-Leste", cca2: "TL", callingCode: ["670"], flag: "🇹🇱" },
  { name: "Togo", cca2: "TG", callingCode: ["228"], flag: "🇹🇬" },
  { name: "Tokelau", cca2: "TK", callingCode: ["690"], flag: "🇹🇰" },
  { name: "Tonga", cca2: "TO", callingCode: ["676"], flag: "🇹🇴" },
  { name: "Trinidad and Tobago", cca2: "TT", callingCode: ["1868"], flag: "🇹🇹" },
  { name: "Tunisia", cca2: "TN", callingCode: ["216"], flag: "🇹🇳" },
  { name: "Turkey", cca2: "TR", callingCode: ["90"], flag: "🇹🇷" },
  { name: "Turkmenistan", cca2: "TM", callingCode: ["993"], flag: "🇹🇲" },
  { name: "Turks and Caicos Islands", cca2: "TC", callingCode: ["1649"], flag: "🇹🇨" },
  { name: "Tuvalu", cca2: "TV", callingCode: ["688"], flag: "🇹🇻" },
  { name: "Uganda", cca2: "UG", callingCode: ["256"], flag: "🇺🇬" },
  { name: "Ukraine", cca2: "UA", callingCode: ["380"], flag: "🇺🇦" },
  { name: "United Arab Emirates", cca2: "AE", callingCode: ["971"], flag: "🇦🇪" },
  { name: "United Kingdom", cca2: "GB", callingCode: ["44"], flag: "🇬🇧" },
  { name: "United States", cca2: "US", callingCode: ["1"], flag: "🇺🇸" },
  { name: "United States Minor Outlying Islands", cca2: "UM", callingCode: ["1"], flag: "🇺🇲" },
  { name: "Uruguay", cca2: "UY", callingCode: ["598"], flag: "🇺🇾" },
  { name: "Uzbekistan", cca2: "UZ", callingCode: ["998"], flag: "🇺🇿" },
  { name: "Vanuatu", cca2: "VU", callingCode: ["678"], flag: "🇻🇺" },
  { name: "Venezuela, Bolivarian Republic of", cca2: "VE", callingCode: ["58"], flag: "🇻🇪" },
  { name: "Viet Nam", cca2: "VN", callingCode: ["84"], flag: "🇻🇳" },
  { name: "Virgin Islands, British", cca2: "VG", callingCode: ["1284"], flag: "🇻🇬" },
  { name: "Virgin Islands, U.S.", cca2: "VI", callingCode: ["1340"], flag: "🇻🇮" },
  { name: "Wallis and Futuna", cca2: "WF", callingCode: ["681"], flag: "🇼🇫" },
  { name: "Western Sahara", cca2: "EH", callingCode: ["212"], flag: "🇪🇭" },
  { name: "Yemen", cca2: "YE", callingCode: ["967"], flag: "🇾🇪" },
  { name: "Zambia", cca2: "ZM", callingCode: ["260"], flag: "🇿🇲" },
  { name: "Zimbabwe", cca2: "ZW", callingCode: ["263"], flag: "🇿🇼" },
];